server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:ecommerce}
    password: ${SPRING_DATASOURCE_PASSWORD:ecommerce}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

order:
  topic: order-events

services:
  product-url: ${PRODUCT_SERVICE_URL:http://localhost:8082}
  inventory-url: ${INVENTORY_SERVICE_URL:http://localhost:8084}
  payment-url: ${PAYMENT_SERVICE_URL:http://localhost:8086}
  cart-url: ${CART_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info
